id: P6484D0C0
initial_creation_type: ocr
source_metadata:
  volumes:
    a7f9b3fa0bad4db88f81a1efd3397c5e:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
